"use client";

import Link from "next/link";
import { ArrowRight, BookOpen, CheckCircle2, Clock3, Headphones, Play, RotateCcw, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { AppShell, PageHeader, SectionTitle } from "@/components/app-shell";
import { ProgressCard } from "@/components/progress-card";
import { mathKnowledgePoints, vocabulary } from "@/lib/content";
import { formatRecordDate, readProgress } from "@/lib/progress";
import { buildTaskPool, getNextRecommendedPoint } from "@/lib/recommendations";
import type { AppProgress } from "@/lib/types";

export function Dashboard() {
  const [progress] = useState<AppProgress>(() => readProgress());
  const mathValue = Math.round((progress.completedKnowledgePoints.length / mathKnowledgePoints.length) * 100);
  const englishValue = Math.round((progress.vocabularyMastered.length / vocabulary.length) * 100);
  const current = getNextRecommendedPoint(progress);
  const tasks = useMemo(() => buildTaskPool(progress), [progress]);
  return <AppShell><div className="mx-auto max-w-6xl px-4 py-8 sm:px-6 lg:px-10 lg:py-12"><PageHeader eyebrow="个人学习空间" title="你好，今天想从哪里继续？" description="这里没有固定的每日计划。根据你的学习记录，选择一个现在最适合的下一步。" />
    <section className="mb-10 grid gap-4 lg:grid-cols-[1.4fr_1fr]"><Link href={`/math/${current.id}`} className="group flex min-h-52 flex-col justify-between rounded-2xl bg-ink p-6 text-white shadow-soft transition hover:-translate-y-0.5 sm:p-8"><div className="flex items-center gap-2 text-sm text-white/65"><Sparkles size={16} />继续学习</div><div><h2 className="mt-8 text-2xl font-bold sm:text-3xl">{current.title}</h2><p className="mt-2 max-w-lg text-sm leading-6 text-white/65">{current.summary}</p></div><div className="mt-6 flex items-center justify-between text-sm"><span className="text-white/60">数学基础 · 函数</span><span className="flex items-center gap-2 font-semibold">开始学习 <ArrowRight size={17} className="transition group-hover:translate-x-1" /></span></div></Link><div className="rounded-2xl border border-line bg-white p-6 shadow-soft"><p className="text-sm font-bold text-ink">现在最值得做的事</p><p className="mt-3 text-xl font-bold leading-8 text-ink">把一个知识点学完，留下清晰记录。</p><div className="mt-5 flex items-center gap-2 text-xs text-muted"><Clock3 size={15} /> 不限时，完成一个小步骤就好</div></div></section>
    <section className="mb-10"><SectionTitle title="学习进度" /><div className="grid gap-4 sm:grid-cols-2"><ProgressCard subject="数学" subtitle={`${progress.completedKnowledgePoints.length}/${mathKnowledgePoints.length} 个知识点完成`} value={mathValue} href="/math" tone="sky" /><ProgressCard subject="英语" subtitle={`${progress.vocabularyMastered.length}/${vocabulary.length} 个单词已掌握`} value={englishValue} href="/english" tone="peach" /></div></section>
    <section className="mb-10"><SectionTitle title="任务池" action={<Link href="/tasks" className="text-sm font-semibold text-muted hover:text-ink">查看全部 <ArrowRight className="ml-1 inline" size={15} /></Link>} /><div className="grid gap-3 md:grid-cols-3">{tasks.slice(0, 3).map((task) => { const Icon = task.kind === "review" ? RotateCcw : task.kind === "practice" ? CheckCircle2 : BookOpen; const tone = task.kind === "review" ? "bg-mint" : task.kind === "practice" ? "bg-peach" : "bg-sky"; return <Link key={task.id} href={task.href} className={`flex items-center gap-4 rounded-2xl border border-line p-4 transition hover:-translate-y-0.5 hover:shadow-soft ${tone}`}><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-white/75"><Icon size={19} /></span><span className="min-w-0"><span className="block truncate text-sm font-bold text-ink">{task.title}</span><span className="mt-1 block text-xs text-muted">{task.reason}</span></span></Link>; })}</div></section>
    <section className="grid gap-6 lg:grid-cols-2"><div><SectionTitle title="推荐学习内容" /><div className="space-y-3"><Link href={`/math/${current.id}`} className="flex items-center gap-4 rounded-2xl border border-line bg-white p-4 hover:shadow-soft"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-sky"><Play size={18} /></span><span className="flex-1"><span className="block text-sm font-bold">{current.title} · 互动学习</span><span className="mt-1 block text-xs text-muted">从当前路径节点开始继续学习</span></span><ArrowRight size={17} className="text-muted" /></Link><Link href="/english/listening" className="flex items-center gap-4 rounded-2xl border border-line bg-white p-4 hover:shadow-soft"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-peach"><Headphones size={18} /></span><span className="flex-1"><span className="block text-sm font-bold">6 Minute English 听力</span><span className="mt-1 block text-xs text-muted">打开具体听力内容集合练习</span></span><ArrowRight size={17} className="text-muted" /></Link></div></div><div><SectionTitle title="最近学习记录" action={<Link href="/history" className="text-sm font-semibold text-muted hover:text-ink">全部记录 <ArrowRight className="ml-1 inline" size={15} /></Link>} /><div className="rounded-2xl border border-line bg-white p-5">{progress.records.length === 0 ? <div className="py-6 text-center"><p className="text-sm font-semibold text-ink">还没有学习记录</p><p className="mt-2 text-xs leading-5 text-muted">完成第一个知识点后，记录会出现在这里。</p></div> : progress.records.slice(0, 4).map((record) => <div key={record.id} className="flex items-center gap-3 border-b border-line py-3 last:border-0"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-mint"><CheckCircle2 size={16} /></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{record.title}</span><span className="text-xs text-muted">{record.action} · {formatRecordDate(record.createdAt)}</span></span></div>)}</div></div></section>
  </div></AppShell>;
}
